include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_constructors_first
    - prefer_single_quotes
    - sort_child_properties_last
    - omit_local_variable_types
    - empty_constructor_bodies
    - prefer_const_constructors